### PR TITLE
44 add adjusted forecast scenario page

### PR DESCRIPTION
**Pull request by amynickolls**
Big one:

Adjusted forecast page added:
- Chart shows forecast post adjustment
- Accordion allows user to cycle through different rates, allow users to select which to edit

Rate adjustment pages (entry, exit and transition) 
- Use dynamic form to save adjustments to the session scenario
- Displays a comparison chart showing base and adjusted forecast once saved
- Offers navigation back to adjusted rate page or option to clear rate adjustments

Clear adjustments button clears all adjustments via clear_adjusted_rates view

Navigate to adjusted page via Start Modelling > Scroll to bottom > Next

### CODE REVIEW

**Comment by tab1tha** [comment]
Hi Amy, 
Going through. 

When I run this branch locally, I haven't succeeded arrive at the adjusted forecast view yet.  This is my workflow:
- it takes me to the `start modelling` page. The filters and graphs all work here. However, 
- When I click on the next button in the modeling page, this error shows up. It's possible that I am not running it correctly too...
image

**Comment by amynickolls** [comment]
> Hi Amy, Going through.
> ...

This is strange - I can't recreate it. Prediction.entry_rates was added in this PR though and the error was coming from a print statement left in there which I've now deleted so perhaps try updating the branch and see what happens?

**Comment by tab1tha** [comment]
> > Hi Amy, Going through.
> > ...
> 
> This is strange - I can't recreate it. Prediction.entry_rates was added in this PR though and the error was coming from a print statement left in there which I've now deleted so perhaps try updating the branch and see what happens?

retrying....

**Review by tab1tha — APPROVED** [review]
Ran this code locally and the views and flows work. 

Side note: All the other pages are on the top bar menu but this page requires that the user first clicks on the start modelling page (as said in the pr description). Is it possible to put it on the top menu too? 
Clicking into a new page and not seeing the switch in the top menu was surprising but it's okay if that was an intentional design decision. 

All good.

**Pull request merged**
